#!/bin/bash
#PBS -P VUR
#PBS -l select=1:ncpus=1:ngpus=1:mem=10GB
#PBS -l walltime=10:00:00
#PBS -j oe

cd /home/jshe2377/frame-interpolation

bash Miniconda3-4.5.11-Linux-x86_64.sh -b -p miniconda

module load cuda/11.2.0

miniconda/bin/conda create -n film python=3.7
source miniconda/bin/activate film

pip install -r requirements.txt

python3 -m training.train \
     --gin_config training/config/film_net-L1.gin \
     --base_folder train_test \
     --label atd_12k
